Repository UbiBelETF/dagger, pull requests merged in 2020-12, with the labels that each got.

#112 Inverted camera window coordinates
  source/dagger/core/graphics/window.cpp
Labels: engine, enhancement, invalid

#122 Aiming System
  source/dagger/gameplay/common/aiming_system.cpp
  source/dagger/gameplay/common/aiming_system.h
Labels: enhancement, feature request, keep open

#138 Example/particle system
  meson.build
  source/dagger/gameplay/common/particles.cpp
  source/dagger/gameplay/common/particles.h
  source/dagger/gameplay/racing/racing_main.cpp
  source/dagger/main.cpp
Labels: enhancement

#144 engine/fix/text_rendering
  source/dagger/core/graphics/text.cpp
  source/dagger/gameplay/tiles_example/tiles_example_main.cpp
Labels: bug, engine

#125 Circular Collisions
  data/textures/Racing/left_camera.png
  data/textures/Racing/red_nsx.png
  data/textures/Racing/right_camera.png
  source/dagger/gameplay/common/simple_collisions.cpp
  source/dagger/gameplay/common/simple_collisions.h
  source/dagger/gameplay/racing/racing_game_logic.cpp
  source/dagger/gameplay/racing/racing_main.cpp
  source/dagger/main.cpp
Labels: enhancement, feature request, keep open

#249 Engine/sound
  data/sounds/music.wav
  source/dagger/core/audio.h
  source/dagger/core/audio_linux.cpp
  source/dagger/core/audio_win.cpp
  source/dagger/core/game.cpp
  source/dagger/gameplay/platformer/platformer_main.cpp
  tools/BuildScripts/main.sharpmake.cs
  tools/Sharpmake/bin/Sharpmake.Application.exe
  tools/Sharpmake/bin/Sharpmake.CommonPlatforms.dll
  tools/Sharpmake/bin/Sharpmake.Generators.dll
  tools/Sharpmake/bin/Sharpmake.dll
Labels: enhancement
