Repository UbiBelETF/dagger, pull requests merged in 2020-11, with the labels that each got.

#11 Rendering sprites now takes z-order into account
  source/dagger/core/graphics/sprite_render.cpp
Labels: enhancement

#30 todo in pingpong was fixed
  source/dagger/gameplay/ping_pong/player_scores.cpp
  source/dagger/gameplay/ping_pong/player_scores.h
Labels: good first issue

#27 Pingpong ball unfair fixed
  source/dagger/gameplay/ping_pong/player_scores.cpp
  source/dagger/gameplay/ping_pong/player_scores.h
  source/dagger/main.cpp
Labels: enhancement, good first issue

#49 IMGUI tool example for PingPong
  source/dagger/gameplay/ping_pong/ping_pong_main.cpp
  source/dagger/gameplay/ping_pong/ping_pong_main.h
  source/dagger/gameplay/ping_pong/pingpong_tools.cpp
  source/dagger/gameplay/ping_pong/pingpong_tools.h
  source/dagger/gameplay/ping_pong/player_scores.h
Labels: enhancement

#56 Added the roll movement for both players in the platformer
  data/input-contexts/arrows.json
  data/input-contexts/asdw.json
  source/dagger/gameplay/platformer/platformer_controller.cpp
  source/dagger/gameplay/platformer/platformer_controller.h
Labels: enhancement

#61 Added the pause game feature
  source/dagger/core/engine.cpp
  source/dagger/core/engine.h
  source/dagger/core/graphics/animations.cpp
  source/dagger/core/system.h
  source/dagger/gameplay/ping_pong/ping_pong_main.cpp
  source/dagger/gameplay/ping_pong/pingpong_tools.cpp
  source/dagger/tools/diagnostics.cpp
Labels: enhancement

#75 Added text rendering to engine. Added TextKnife, the font spritesheet prep tool.
  data/animations/dungeon/random.json
  data/spritesheets/pixel-font.png
  data/spritesheets/pixel-font.spritesheet
  source/dagger/core/graphics/text.cpp
  source/dagger/core/graphics/text.h
  source/dagger/gameplay/tiles_example/tiles_example_main.cpp
  tools/TextKnife/Program.cs
  tools/TextKnife/TextKnife.csproj
  tools/TextKnife/TextKnife.sln
  tools/TextKnife/obj/TextKnife.csproj.nuget.dgspec.json
  tools/TextKnife/obj/TextKnife.csproj.nuget.g.props
  tools/TextKnife/obj/TextKnife.csproj.nuget.g.targets
  tools/TextKnife/obj/project.assets.json
  tools/TextKnife/obj/project.nuget.cache
Labels: engine, enhancement

#73 Engine/sprite atlas
  data/animations/dungeon/random.json
  data/shaders/standard.fs.glsl
  data/shaders/standard.vs.glsl
  data/spritesheets/dungeon.png
  data/spritesheets/dungeon.spritesheet
  data/spritesheets/pixel-font.png
  data/spritesheets/pixel-font.spritesheet
  data/tiles_example.ini
  source/dagger/core/graphics/animation.h
  source/dagger/core/graphics/animations.cpp
  source/dagger/core/graphics/sprite.cpp
  source/dagger/core/graphics/sprite.h
  source/dagger/core/graphics/sprite_render.cpp
  source/dagger/core/graphics/sprite_render.h
  source/dagger/core/graphics/text.cpp
  source/dagger/core/graphics/text.h
  source/dagger/core/graphics/texture.h
  source/dagger/core/graphics/textures.cpp
  source/dagger/gameplay/ping_pong/ping_pong_main.cpp
  source/dagger/gameplay/platformer/platformer_main.cpp
  source/dagger/gameplay/racing/racing_main.cpp
  source/dagger/gameplay/team_game/team_game_main.cpp
  source/dagger/gameplay/tiles_example/tiles_example_main.cpp
  source/dagger/gameplay/tiles_example/tiles_example_main.h
  source/dagger/main.cpp
  tools/TextKnife/Program.cs
  tools/TextKnife/TextKnife.csproj
  tools/TextKnife/TextKnife.sln
  tools/TextKnife/obj/TextKnife.csproj.nuget.dgspec.json
  tools/TextKnife/obj/TextKnife.csproj.nuget.g.props
  tools/TextKnife/obj/TextKnife.csproj.nuget.g.targets
  tools/TextKnife/obj/project.assets.json
  tools/TextKnife/obj/project.nuget.cache
Labels: engine, enhancement
